test1 = function(n) rmixnorm(n, 
                             Pi = c(0.2, 0.3, 0.5), 
                             Mu = array(c(0, 0,
                                          3, 0,
                                          2, 0), dim = c(2,3)),
                             S = array(c(1,0,
                                         0,1,
                                         0.2,0,
                                         0,0.2,
                                         0.0005,0,
                                         0,0.5), dim = c(2,2,3)))